language: python
python:
  - "3.6"
services:
  - docker
install:
  - docker build -t max-question-answering-web-app .
  - docker run -it -d -p 5000:5000 max-question-answering-web-app
  - pip install -r test-requirements.txt
before_script:
  - pip install -r requirements.txt
script:
  - flake8 . --max-line-length=127
