language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
before_install:
  - docker build -t max-question-answering-web-app .
  - docker run -it -d -p 5000:5000 max-question-answering-web-app
  - sleep 30
  - pip install -r requirements.txt
install:
  - python app.py &
  - sleep 90
  - pip install -r test-requirements.txt
script:
  - flake8 . --max-line-length=127
